linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/gortc
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - sloppyReassign

issues:
  exclude:
    - "hugeParam: (o|options|opt) is heavy"
    - "`n` can be `expvar.Var`"
    - "use strings.ReplaceAll method"
    - "string `(allow|drop|pass)` has \\d occurrences,"
  exclude-rules:
    - text: "string `<nil>`"
      linters:
        - goconst

    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Ease some gocritic warnings on test files.
    - path: _test\.go
      text: "(unnamedResult|exitAfterDefer|unlambda)"
      linters:
        - gocritic

    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via "nolint" comments.
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: internal/hmac/
      text: "Write\\` is not checked"
      linters:
        - errcheck

    # Ease linting on benchmarking code.
    - path: cmd/stun-bench/
      linters:
        - gosec
        - errcheck
        - unparam

    - path: ^cmd/
      linters:
        - gocyclo
    - path: ^(cmd/|internal/cli)
      text: "(unnamedResult|exitAfterDefer)"
      linters:
        - gocritic

    - text: "\\(\\*Server\\)\\.processMessage"
      linters:
        - gocyclo

    - text: "\"err\" shadows declaration"
      path: _test\.go

    - text: "rangeValCopy"
      path: "internal/testutil/logs"

    - path: "internal/server/worker_pool"
      text: "struct of size 120 bytes could be of size 112 bytes"

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - scopelint

run:
  skip-dirs:
    - e2e
    - fuzz
    - testdata
    - api

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.13.x # use fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed"
