version: '3.4'

services:
  turn-peer:
    container_name: ci_turn-peer_1
    entrypoint:
      - turn-client
      - peer
    depends_on:
      - turn-server
    links:
      - turn-server
    build:
      context: turn-client
      dockerfile: "Dockerfile"
      network: nat
      args:
        CI_GO_VERSION: latest
  turn-client:
    container_name: ci_turn-client_1
    depends_on:
      - turn-server
      - turn-peer
    links:
      - turn-server
      - turn-peer
    build:
      context: turn-client
      dockerfile: "Dockerfile"
      network: nat
      args:
        CI_GO_VERSION: latest
  turn-server:
    container_name: ci_turn-server_1
    build:
      context: ../..
      network: nat
      dockerfile: "e2e/gortc-turn/server.Dockerfile"
networks:
  default:
    external:
      name: nat
